"""Added tables for crop health

Revision ID: 03c460a70be7
Revises: d6588eefb5bd
Create Date: 2026-08-27 18:44:38.275292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c460a70be7'
down_revision: Union[str, Sequence[str], None] = 'd6588eefb5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('ndvi', sa.Float(), nullable=False),
    sa.Column('stressed_area_percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health_trend', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_health_metrics_field_id'), 'crop_health_metrics', ['field_id'], unique=False)
    op.create_index(op.f('ix_crop_health_metrics_id'), 'crop_health_metrics', ['id'], unique=False)
    op.create_table('stress_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_health_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['crop_health_id'], ['crop_health_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_zones_id'), 'stress_zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_zones_id'), table_name='stress_zones')
    op.drop_table('stress_zones')
    op.drop_index(op.f('ix_crop_health_metrics_id'), table_name='crop_health_metrics')
    op.drop_index(op.f('ix_crop_health_metrics_field_id'), table_name='crop_health_metrics')
    op.drop_table('crop_health_metrics')
    # ### end Alembic commands ###
