"""initial_schema

Revision ID: 3bde463894ca
Revises: 
Create Date: 2026-08-29 15:20:48.434670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bde463894ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('ndvi', sa.Float(), nullable=False),
    sa.Column('stressed_area_percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health_trend', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_health_metrics_field_id'), 'crop_health_metrics', ['field_id'], unique=False)
    op.create_index(op.f('ix_crop_health_metrics_id'), 'crop_health_metrics', ['id'], unique=False)
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_health', sa.Float(), nullable=True),
    sa.Column('total_fields', sa.Float(), nullable=True),
    sa.Column('active_alerts', sa.Float(), nullable=True),
    sa.Column('next_irrigation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_area', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('date_of_sowing', sa.Date(), nullable=False),
    sa.Column('date_of_harvest', sa.Date(), nullable=False),
    sa.Column('crop_type', sa.Enum('WHEAT', 'RICE', 'COTTON', 'MAIZE', 'VEGETABLES', name='croptype'), nullable=False),
    sa.Column('soil_type', sa.Enum('LOAMY', 'CLAYLOAM', 'SANDYLOAM', 'ALLUVIAL', 'BLACKSOIL', name='soiltype'), nullable=False),
    sa.Column('boundary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.create_table('stress_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_health_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['crop_health_id'], ['crop_health_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_zones_id'), 'stress_zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_zones_id'), table_name='stress_zones')
    op.drop_table('stress_zones')
    op.drop_index(op.f('ix_fields_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('field_form')
    op.drop_table('dashboard')
    op.drop_index(op.f('ix_crop_health_metrics_id'), table_name='crop_health_metrics')
    op.drop_index(op.f('ix_crop_health_metrics_field_id'), table_name='crop_health_metrics')
    op.drop_table('crop_health_metrics')
    # ### end Alembic commands ###
