"""add crop_analyses table

Revision ID: 587a0bd9383b
Revises: 3b377f033a71
Create Date: 2026-09-01 06:03:20.064803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587a0bd9383b'
down_revision: Union[str, Sequence[str], None] = '3b377f033a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('treatment', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_analyses_user_id'), 'crop_analyses', ['user_id'], unique=False)
    op.add_column('dashboard', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_dashboard_user_id'), 'dashboard', ['user_id'], unique=False)
    op.create_foreign_key(None, 'dashboard', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_field_form_user_id'), 'field_form', ['user_id'], unique=False)
    op.create_foreign_key(None, 'field_form', 'users', ['user_id'], ['id'])
    op.alter_column('otp_verifications', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_otp_verifications_id'), table_name='otp_verifications')
    op.drop_index(op.f('idx_otp_verifications_mobile_number'), table_name='otp_verifications')
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_mobile_number'), 'otp_verifications', ['mobile_number'], unique=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_otp_verifications_mobile_number'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.create_index(op.f('idx_otp_verifications_mobile_number'), 'otp_verifications', ['mobile_number'], unique=False)
    op.create_index(op.f('idx_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.alter_column('otp_verifications', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'field_form', type_='foreignkey')
    op.drop_index(op.f('ix_field_form_user_id'), table_name='field_form')
    op.drop_constraint(None, 'dashboard', type_='foreignkey')
    op.drop_index(op.f('ix_dashboard_user_id'), table_name='dashboard')
    op.drop_column('dashboard', 'user_id')
    op.drop_index(op.f('ix_crop_analyses_user_id'), table_name='crop_analyses')
    op.drop_table('crop_analyses')
    # ### end Alembic commands ###
