"""Adding the table

Revision ID: 5b001aa8c5a4
Revises: 
Create Date: 2026-08-25 21:11:27.513621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b001aa8c5a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_health', sa.Float(), nullable=True),
    sa.Column('total_fields', sa.Float(), nullable=True),
    sa.Column('active_alerts', sa.Float(), nullable=True),
    sa.Column('next_irrigation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard')
    # ### end Alembic commands ###
