"""add user_id to dashboard, field_form, crop_analyses

Revision ID: a296b12b3706
Revises: b1adecc770af
Create Date: 2026-08-30 15:23:33.524092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a296b12b3706'
down_revision: Union[str, Sequence[str], None] = 'b1adecc770af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_analyses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_crop_analyses_user_id'), 'crop_analyses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'crop_analyses', 'users', ['user_id'], ['id'])
    op.add_column('dashboard', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_dashboard_user_id'), 'dashboard', ['user_id'], unique=False)
    op.create_foreign_key(None, 'dashboard', 'users', ['user_id'], ['id'])
    op.add_column('field_form', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_field_form_user_id'), 'field_form', ['user_id'], unique=False)
    op.create_foreign_key(None, 'field_form', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field_form', type_='foreignkey')
    op.drop_index(op.f('ix_field_form_user_id'), table_name='field_form')
    op.drop_column('field_form', 'user_id')
    op.drop_constraint(None, 'dashboard', type_='foreignkey')
    op.drop_index(op.f('ix_dashboard_user_id'), table_name='dashboard')
    op.drop_column('dashboard', 'user_id')
    op.drop_constraint(None, 'crop_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_crop_analyses_user_id'), table_name='crop_analyses')
    op.drop_column('crop_analyses', 'user_id')
    # ### end Alembic commands ###
