"""Sync user, dashboard, and field_form relationships

Revision ID: b2e75577bb0d
Revises: a296b12b3706
Create Date: 2026-09-01 01:58:26.192869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e75577bb0d'
down_revision: Union[str, Sequence[str], None] = 'a296b12b3706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
