"""add field_form table

Revision ID: d6588eefb5bd
Revises: 
Create Date: 2026-08-27 14:56:17.406802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6588eefb5bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_area', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('date_of_sowing', sa.Date(), nullable=False),
    sa.Column('date_of_harvest', sa.Date(), nullable=False),
    sa.Column('crop_type', sa.Enum('WHEAT', 'RICE', 'COTTON', 'MAIZE', 'VEGETABLES', name='croptype'), nullable=False),
    sa.Column('soil_type', sa.Enum('LOAMY', 'CLAYLOAM', 'SANDYLOAM', 'ALLUVIAL', 'BLACKSOIL', name='soiltype'), nullable=False),
    sa.Column('boundary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_form')
    # ### end Alembic commands ###
