export const VIDEO_DEMO_URL = "https://www.youtube.com/watch?v=FasAI-Demo-ReplaceMe";
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";

export const navItems = [
  { key: "home", href: "/" },
  { key: "about", href: "/about" },
  { key: "howItWorks", href: "/how-it-works" },
  { key: "contact", href: "/contact" }
];

export const dashboardItems = [
  { key: "dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { key: "fields", href: "/fields", icon: "Map" },
  { key: "satellite", href: "/satellite", icon: "Satellite" },
  { key: "weather", href: "/weather", icon: "CloudSun" },
  { key: "cropHealth", href: "/crop-health", icon: "Sprout" },
  { key: "alerts", href: "/alerts", icon: "Bell" },
  { key: "assistant", href: "/diagnose", icon: "Bot" },
  { key: "reports", href: "/analytics", icon: "FileBarChart" },
  { key: "settings", href: "/settings", icon: "Settings" }
];

export const copy = {
  en: {
    home: "Home", about: "About", howItWorks: "How It Works", contact: "Contact",
    login: "Login", register: "Register", logout: "Logout", language: "हिंदी",
    getStarted: "Get Started", learnHow: "How It Works", watchDemo: "Watch YouTube Demo", aiMonitoring: "AI-powered crop monitoring", slide: "slide", fieldIntelligence: "FasAI Field Intelligence", liveMonitoring: "Live monitoring concept", seeChanges: "See changes before they become losses.",
    heroTitle1: "Keep Your Crops", heroTitle2: "Healthy With", heroTitle3: "Smart Technology",
    heroText: "Monitor your fields, understand crop health and get simple, timely recommendations with AI-powered insights.",
    helps: "How FasAI Helps You",
    uploadPhoto: "Upload a Crop Photo", uploadText: "Upload a clear crop image and let FasAI check visible symptoms.",
    checkHealth: "Check Crop Health", healthText: "Combine satellite, soil, weather and image signals to understand field health.",
    recommendations: "Get Recommendations", recText: "Receive easy-to-understand actions for irrigation, nutrition and crop protection.",
    monitoring: "Start Monitoring Your Crops Today", monitoringText: "Create your fields, track changes and act before small problems become big losses.",
    registerNow: "Register Now", secure: "Secure & Reliable", farmerFriendly: "Farmer Friendly", quick: "Quick Results", support: "Support",
    secureText: "Your data stays protected.", farmerText: "Simple steps for every farmer.", quickText: "Get useful insights quickly.", supportText: "Help when you need it.",
    dashboard: "Dashboard", fields: "Fields", satellite: "Satellite Monitor", weather: "Weather", cropHealth: "Crop Health",
    alerts: "Alerts", assistant: "AI Assistant", reports: "Reports", settings: "Settings", soil: "Soil", pestRisk: "Pest Risk",
    addField: "Add New Field", search: "Search fields...", fieldDetails: "Field Details", healthScore: "Health Score",
    healthy: "Healthy", moderate: "Moderate", stressed: "Stressed", createField: "Create Field",
    fieldName: "Field Name", cropType: "Crop Type", area: "Area", location: "Location", soilType: "Soil Type",
    sowingDate: "Date of Sowing", harvestingDate: "Expected Harvest", selectBoundary: "Select field boundary on map",
    save: "Save", cancel: "Cancel", noData: "No live data yet — showing demo data.",
    overview: "Overview", recentAlerts: "Recent Alerts", viewAll: "View All", temperature: "Temperature",
    humidity: "Humidity", rainfall: "Rainfall", moisture: "Soil Moisture", ndvi: "NDVI",
    healthTrend: "Health Trend", stressZones: "Stress Zones", analyze: "Analyze Field", back: "Back",
    send: "Send", askAssistant: "Ask FasAI", uploadImage: "Upload Image", typeMessage: "Type your question...",
    reportsDesc: "Field reports, health trends and downloadable assessment summaries.",
    welcomeDashboard: "Welcome back, Farmer 👋", overallCropHealth: "Overall Crop Health", totalFields: "Total Fields",
    activeAlerts: "Active Alerts", nextIrrigation: "Next Irrigation", requiresAttention: "Requires Attention", days: "Days",
    northField: "North Field", southField: "South Field", eastField: "East Field", northWest: "North-West", southEast: "South-East", good: "Good", activeFields: "Active fields", openMap: "Open Satellite Monitor",
    demoNdvi: "Demo satellite layer • 10 m resolution target", layerNdvi: "NDVI", layerTrueColor: "True Color", layerMoisture: "Moisture",
    zoomIn: "Zoom in", zoomOut: "Zoom out", highPestRisk: "High Pest Risk", waterStress: "Water Stress Detected", rainfallAlert: "Rainfall Alert",
    critical: "Critical", warning: "Warning", info: "Info", profileRole: "Farmer", profileName: "Ramesh Kumar",
    menu: "Menu", close: "Close",
    aboutTitle: "Agriculture intelligence made practical",
    aboutText: "FasAI brings field maps, satellite monitoring, weather, soil signals and AI assistance into one farmer-friendly workspace. The goal is to help farmers notice stress early, understand where it is happening and decide what to do next.",
    aboutPoints: [
      ["Field intelligence", "Draw your field boundary and keep each crop, area and location organized in one place."],
      ["Weather-aware decisions", "Use temperature, humidity, rainfall and soil moisture signals to understand changing field conditions."],
      ["Crop health monitoring", "Track NDVI, health scores and stress zones so attention can be focused where it matters."],
      ["Farmer-first design", "Large controls, simple language and mobile-friendly screens keep the experience practical in the field."]
    ],
    aboutClosingTitle: "From field data to a simple next step",
    aboutClosingText: "FasAI is designed to bring multiple signals together instead of making farmers search through separate tools. The frontend keeps maps, health, weather, alerts, reports and AI assistance connected so a farmer can move from observation to action quickly.",
    howTitle: "How FasAI Works", howText: "FasAI follows a simple flow: define your field, collect signals, calculate crop-health indicators, detect stress and turn the results into actions.",
    howSteps: [
      ["Create your field", "Choose the location, enter crop and soil details, then draw the field boundary on the map."],
      ["Collect field signals", "Satellite imagery, weather and soil observations become the inputs for field monitoring."],
      ["Analyze crop health", "FasAI turns those signals into health scores, NDVI trends and stress indicators."],
      ["Get early warnings", "Alerts highlight important changes such as crop stress, pest risk or unusual conditions."],
      ["Ask the AI assistant", "Upload a crop image or ask a question to get a simple explanation and suggested next steps."]
    ],
    contactTitle: "We are here to help", contactText: "For product questions, demonstrations or implementation support, use the contact details below.",
    email: "Email", phone: "Phone", location: "Location", sendMessage: "Send us a message", name: "Name", message: "Message", sendMessageButton: "Send Message",
    emailValue: "support@fasai.example", phoneValue: "+91 00000 00000", locationValue: "India • Agriculture support", contactFaqTitle: "Frequently Asked Questions",
    contactFaq: [["Is FasAI mobile friendly?", "Yes. The interface is designed mobile-first so farmers can use it comfortably in the field."], ["Does it use satellite data?", "The demo UI is prepared for Sentinel-2 based monitoring and can connect to the backend data pipeline."], ["Can I use Hindi?", "Yes. Use the Hindi / English pill in the top navigation to switch the complete interface."]],
    otpTitle: "Verify your mobile number", otpText: "We sent a 6-digit OTP to your mobile number.", verify: "Verify OTP", resend: "Resend OTP",
    mobile: "Mobile Number", fullName: "Full Name", enterName: "Enter your full name", enterMobile: "Enter your mobile number",
    continue: "Continue", createAccount: "Create Your Account", welcomeBack: "Welcome Back!",
    loginText: "Login to continue monitoring your crops.", registerText: "Join FasAI and start monitoring your crops smarter.",
    invalidOtp: "Demo OTP is 123456.", demoMode: "Demo mode", dashboardDescription: "A simple view of crop health, field activity and important alerts.",
    satelliteTitle: "Satellite Monitoring", satelliteDescription: "Inspect the demo satellite layer for your field and compare vegetation signals.",
    satelliteHealthy: "Healthy vegetation signal", lowNdviZones: "Low-NDVI zones", stress: "Stress", healthyLabel: "Healthy", dataPipeline: "Data pipeline",
    satellitePipelineText: "Sentinel-2 Band 4 + Band 8 → NDVI → field mask → zonal statistics → ML health score.",
    today: "Today", tomorrow: "Tomorrow", weatherTitle: "Weather", weatherDescription: "Current conditions and a short forecast for your field.", forecast: "5-day forecast", rainChance: "rain", demoWeather: "Demo weather data. Connect the backend to OpenWeather using the field centroid when the API key is configured.",
    alertsDescription: "Prioritized field notifications and recommended next actions.", markReviewed: "Mark as reviewed", justNow: "Just now", twoHours: "2 hr ago", yesterday: "Yesterday",
    cropHealthTitle: "Crop Health", cropHealthDescription: "Health score, NDVI trend and localized stress zones.", stressedArea: "Stressed area", status: "Status",
    assistantTitle: "AI Assistant", assistantDescription: "Upload a crop image or ask questions about your field.",
    settingsDescription: "Manage language, account preferences and notification controls.", settingsLanguage: "Language", settingsNotifications: "Notifications", enabled: "Enabled",
    fieldsDescription: "Manage your fields, crop details and field boundaries.", aphid: "Aphid", stemBorer: "Stem borer", fungalDisease: "Fungal disease", pestRiskNote: "Warm and humid conditions can increase disease pressure.", pestRiskTitle: "Pest & Disease Risk", pestRiskDescription: "Risk indicators based on field conditions and weather.", overallRisk: "Overall risk", riskByThreat: "Risk by threat", suggestedPrevention: "Suggested prevention",
    prevention1: "Inspect leaves in the high-risk zones.", prevention2: "Avoid unnecessary spraying; confirm the cause first.", prevention3: "Monitor humidity and rainfall after wet days.",
    soilTitle: "Soil Monitoring", soilDescription: "Sensor and soil-profile indicators for your field.", soilProfile: "Soil profile", recommendation: "Recommendation", phosphorus: "Phosphorus", organicCarbon: "Organic Carbon", texture: "Texture", soilRecommendation: "Maintain current irrigation and add organic matter after harvest.",
    analyticsChange: "7-day health change", reportsGenerated: "Reports generated", fieldsMonitored: "Fields monitored", recentReports: "Recent assessment reports", generated: "Generated", view: "View", downloadPdf: "Download PDF",
    fieldCreated: "Field created successfully. Review details and continue monitoring.", newField: "New Field", cropHealthCard: "NDVI, health score and stressed zones.", soilCard: "Moisture, pH and nutrients.", pestCard: "Risk flags and preventive actions.",
    alertPestText: "North Field shows conditions that may increase pest pressure.", alertWaterText: "South-East sector has low NDVI and soil moisture.", alertRainText: "Light rain is expected within the next 48 hours.", assistantWelcome: "Namaste! I am FasAI Assistant. Upload a crop photo or ask me about crop health, soil, pests or irrigation.", assistantDemo: "Demo assistant", assistantDemoResponse: "Demo response: I would combine your field health, weather, soil and image signals here. Connect this screen to your AI API for the live recommendation.", wheat: "Wheat", rice: "Rice", maize: "Maize", cotton: "Cotton", vegetables: "Vegetables", loamy: "Loamy", clayLoam: "Clay Loam", sandyLoam: "Sandy Loam", blackSoil: "Black Soil", alluvial: "Alluvial", wind: "Wind", nitrogen: "Nitrogen", potassium: "Potassium", weeklyHealth: "Weekly Health", waterStressReport: "Water Stress", pestRiskReport: "Pest Risk", footerAbout: "About", footerContact: "Contact", footerCopyright: "Smart crop intelligence."
  },
  hi: {
    home: "होम", about: "हमारे बारे में", howItWorks: "कैसे काम करता है", contact: "संपर्क",
    login: "लॉगिन", register: "रजिस्टर", logout: "लॉगआउट", language: "English",
    getStarted: "शुरू करें", learnHow: "कैसे काम करता है", watchDemo: "YouTube डेमो देखें", aiMonitoring: "AI आधारित फसल निगरानी", slide: "स्लाइड", fieldIntelligence: "FasAI खेत की जानकारी", liveMonitoring: "लाइव मॉनिटरिंग", seeChanges: "समस्या नुकसान बनने से पहले बदलाव देखें।",
    heroTitle1: "अपनी फसलों को रखें", heroTitle2: "स्वस्थ और सुरक्षित", heroTitle3: "स्मार्ट तकनीक के साथ",
    heroText: "अपने खेतों की निगरानी करें, फसल का स्वास्थ्य समझें और AI की मदद से समय पर आसान सुझाव पाएं।",
    helps: "FasAI आपकी कैसे मदद करता है",
    uploadPhoto: "फसल की फोटो अपलोड करें", uploadText: "फसल की साफ तस्वीर अपलोड करें और FasAI दिखाई देने वाले लक्षणों की जांच करेगा।",
    checkHealth: "फसल का स्वास्थ्य जांचें", healthText: "सैटेलाइट, मिट्टी, मौसम और फोटो से मिली जानकारी को मिलाकर खेत का स्वास्थ्य समझें।",
    recommendations: "सुझाव पाएं", recText: "सिंचाई, पोषण और फसल सुरक्षा के लिए आसान और उपयोगी कदम पाएं।",
    monitoring: "आज ही अपनी फसलों की निगरानी शुरू करें", monitoringText: "अपने खेत जोड़ें, बदलाव देखें और छोटी समस्या को बड़ा नुकसान बनने से पहले पहचानें।",
    registerNow: "अभी रजिस्टर करें", secure: "सुरक्षित और भरोसेमंद", farmerFriendly: "किसान के लिए आसान", quick: "तेज़ परिणाम", support: "सहायता",
    secureText: "आपका डेटा सुरक्षित रहता है।", farmerText: "हर किसान के लिए आसान चरण।", quickText: "जल्दी उपयोगी जानकारी पाएं।", supportText: "जरूरत पर सहायता।",
    dashboard: "डैशबोर्ड", fields: "खेत", satellite: "सैटेलाइट मॉनिटर", weather: "मौसम", cropHealth: "फसल स्वास्थ्य",
    alerts: "अलर्ट", assistant: "AI सहायक", reports: "रिपोर्ट", settings: "सेटिंग्स", soil: "मिट्टी", pestRisk: "कीट जोखिम",
    addField: "नया खेत जोड़ें", search: "खेत खोजें...", fieldDetails: "खेत का विवरण", healthScore: "स्वास्थ्य स्कोर",
    healthy: "स्वस्थ", moderate: "मध्यम", stressed: "तनावग्रस्त", createField: "खेत बनाएं",
    fieldName: "खेत का नाम", cropType: "फसल का प्रकार", area: "क्षेत्रफल", location: "स्थान", soilType: "मिट्टी का प्रकार",
    sowingDate: "बुवाई की तारीख", harvestingDate: "अनुमानित कटाई", selectBoundary: "मानचित्र पर खेत की सीमा चुनें",
    save: "सहेजें", cancel: "रद्द करें", noData: "अभी लाइव डेटा नहीं है — डेमो डेटा दिखाया जा रहा है।",
    overview: "अवलोकन", recentAlerts: "हाल के अलर्ट", viewAll: "सभी देखें", temperature: "तापमान",
    humidity: "नमी", rainfall: "वर्षा", moisture: "मिट्टी की नमी", ndvi: "NDVI",
    healthTrend: "स्वास्थ्य ट्रेंड", stressZones: "तनाव क्षेत्र", analyze: "खेत का विश्लेषण", back: "वापस",
    send: "भेजें", askAssistant: "FasAI से पूछें", uploadImage: "फोटो अपलोड करें", typeMessage: "अपना सवाल लिखें...",
    reportsDesc: "खेत की रिपोर्ट, स्वास्थ्य ट्रेंड और मूल्यांकन सारांश।",
    welcomeDashboard: "वापसी पर स्वागत है, किसान 👋", overallCropHealth: "कुल फसल स्वास्थ्य", totalFields: "कुल खेत",
    activeAlerts: "सक्रिय अलर्ट", nextIrrigation: "अगली सिंचाई", requiresAttention: "ध्यान आवश्यक", days: "दिन",
    northField: "नॉर्थ फील्ड", southField: "साउथ फील्ड", eastField: "ईस्ट फील्ड", northWest: "उत्तर-पश्चिम", southEast: "दक्षिण-पूर्व", good: "अच्छा", activeFields: "सक्रिय खेत", openMap: "सैटेलाइट मॉनिटर खोलें",
    demoNdvi: "डेमो सैटेलाइट लेयर • 10 मीटर रिज़ॉल्यूशन लक्ष्य", layerNdvi: "NDVI", layerTrueColor: "सच्चा रंग", layerMoisture: "नमी",
    zoomIn: "ज़ूम बढ़ाएं", zoomOut: "ज़ूम घटाएं", highPestRisk: "कीट का उच्च जोखिम", waterStress: "पानी की कमी का संकेत", rainfallAlert: "बारिश का अलर्ट",
    critical: "गंभीर", warning: "चेतावनी", info: "जानकारी", profileRole: "किसान", profileName: "रमेश कुमार",
    menu: "मेन्यू", close: "बंद करें",
    aboutTitle: "खेती की समझ को आसान और उपयोगी बनाना",
    aboutText: "FasAI खेत के मानचित्र, सैटेलाइट मॉनिटरिंग, मौसम, मिट्टी के संकेत और AI सहायता को एक आसान workspace में लाता है। उद्देश्य है तनाव को जल्दी पहचानना, उसका स्थान समझना और अगला कदम तय करना।",
    aboutPoints: [["खेत की जानकारी", "खेत की सीमा बनाएं और हर फसल, क्षेत्रफल व स्थान को एक जगह व्यवस्थित रखें."], ["मौसम के आधार पर निर्णय", "तापमान, नमी, वर्षा और मिट्टी की नमी के संकेतों से बदलती परिस्थितियों को समझें."], ["फसल स्वास्थ्य निगरानी", "NDVI, स्वास्थ्य स्कोर और तनाव क्षेत्रों को देखकर सही जगह पर ध्यान दें."], ["किसान-केंद्रित डिज़ाइन", "बड़े बटन, आसान भाषा और मोबाइल-अनुकूल स्क्रीन खेत में उपयोग को सरल बनाते हैं."]],
    aboutClosingTitle: "खेत के डेटा से आसान अगला कदम", aboutClosingText: "FasAI अलग-अलग टूल खोजने की जरूरत कम करने के लिए कई संकेतों को एक जगह लाता है। मानचित्र, स्वास्थ्य, मौसम, अलर्ट, रिपोर्ट और AI सहायता एक साथ जुड़े रहते हैं ताकि किसान जल्दी निर्णय ले सके।",
    howTitle: "FasAI कैसे काम करता है", howText: "FasAI का प्रवाह सरल है: खेत बनाएं, डेटा संकेत लें, फसल स्वास्थ्य संकेतक निकालें, तनाव पहचानें और परिणाम को उपयोगी कदमों में बदलें।",
    howSteps: [["खेत बनाएं", "स्थान चुनें, फसल और मिट्टी की जानकारी भरें और मानचित्र पर खेत की सीमा बनाएं."], ["खेत के संकेत जुटाएं", "सैटेलाइट तस्वीरें, मौसम और मिट्टी की जानकारी खेत की निगरानी के लिए इनपुट बनती हैं."], ["फसल स्वास्थ्य का विश्लेषण करें", "FasAI इन संकेतों से स्वास्थ्य स्कोर, NDVI ट्रेंड और तनाव संकेत तैयार करता है."], ["समय पर चेतावनी पाएं", "अलर्ट फसल तनाव, कीट जोखिम या असामान्य परिस्थितियों जैसे महत्वपूर्ण बदलाव दिखाते हैं."], ["AI सहायक से पूछें", "फसल की फोटो अपलोड करें या सवाल पूछें और आसान जवाब व अगला कदम पाएं."]],
    contactTitle: "हम आपकी सहायता के लिए हैं", contactText: "उत्पाद, डेमो या तकनीकी सहायता के लिए नीचे दिए गए संपर्क विकल्पों का उपयोग करें।",
    email: "ईमेल", phone: "फोन", location: "स्थान", sendMessage: "हमें संदेश भेजें", name: "नाम", message: "संदेश", sendMessageButton: "संदेश भेजें",
    emailValue: "support@fasai.example", phoneValue: "+91 00000 00000", locationValue: "भारत • कृषि सहायता", contactFaqTitle: "अक्सर पूछे जाने वाले सवाल",
    contactFaq: [["क्या FasAI मोबाइल पर चलता है?", "हाँ। इंटरफेस मोबाइल-फर्स्ट है ताकि किसान खेत में आसानी से इसका उपयोग कर सके."], ["क्या इसमें सैटेलाइट डेटा है?", "डेमो UI Sentinel-2 आधारित मॉनिटरिंग के लिए तैयार है और बैकएंड डेटा पाइपलाइन से जुड़ सकता है."], ["क्या मैं हिंदी इस्तेमाल कर सकता हूँ?", "हाँ। ऊपर दिए हिंदी / English बटन से पूरा इंटरफेस बदला जा सकता है."]],
    otpTitle: "मोबाइल नंबर सत्यापित करें", otpText: "हमने आपके मोबाइल नंबर पर 6 अंकों का OTP भेजा है।", verify: "OTP सत्यापित करें", resend: "OTP दोबारा भेजें",
    mobile: "मोबाइल नंबर", fullName: "पूरा नाम", enterName: "अपना पूरा नाम लिखें", enterMobile: "मोबाइल नंबर लिखें",
    continue: "आगे बढ़ें", createAccount: "अपना खाता बनाएं", welcomeBack: "वापसी पर स्वागत है!",
    loginText: "अपनी फसलों की निगरानी जारी रखने के लिए लॉगिन करें।", registerText: "FasAI से जुड़ें और स्मार्ट तरीके से फसलों की निगरानी शुरू करें।",
    invalidOtp: "डेमो OTP 123456 है।", demoMode: "डेमो मोड", dashboardDescription: "फसल स्वास्थ्य, खेत की गतिविधि और महत्वपूर्ण अलर्ट का आसान सारांश।",
    satelliteTitle: "सैटेलाइट मॉनिटरिंग", satelliteDescription: "अपने खेत की डेमो सैटेलाइट लेयर देखें और वनस्पति संकेतों की तुलना करें।",
    satelliteHealthy: "स्वस्थ वनस्पति संकेत", lowNdviZones: "कम-NDVI क्षेत्र", stress: "तनाव", healthyLabel: "स्वस्थ", dataPipeline: "डेटा पाइपलाइन",
    satellitePipelineText: "Sentinel-2 Band 4 + Band 8 → NDVI → field mask → zonal statistics → ML health score.",
    today: "आज", tomorrow: "कल", weatherTitle: "मौसम", weatherDescription: "आपके खेत की वर्तमान स्थिति और छोटा पूर्वानुमान।", forecast: "5 दिन का पूर्वानुमान", rainChance: "बारिश", demoWeather: "डेमो मौसम डेटा। API key कॉन्फ़िगर होने पर बैकएंड को OpenWeather से जोड़ा जा सकता है।",
    alertsDescription: "महत्व के अनुसार खेत के अलर्ट और अगले कदम।", markReviewed: "समीक्षित के रूप में चिन्हित करें", justNow: "अभी", twoHours: "2 घंटे पहले", yesterday: "कल",
    cropHealthTitle: "फसल स्वास्थ्य", cropHealthDescription: "स्वास्थ्य स्कोर, NDVI ट्रेंड और स्थानीय तनाव क्षेत्र।", stressedArea: "तनावग्रस्त क्षेत्र", status: "स्थिति",
    assistantTitle: "AI सहायक", assistantDescription: "फसल की फोटो अपलोड करें या अपने खेत के बारे में सवाल पूछें।",
    settingsDescription: "भाषा, खाता प्राथमिकताएं और नोटिफिकेशन नियंत्रित करें।", settingsLanguage: "भाषा", settingsNotifications: "नोटिफिकेशन", enabled: "चालू",
    fieldsDescription: "अपने खेत, फसल की जानकारी और सीमाओं को प्रबंधित करें।", aphid: "माहू", stemBorer: "तना छेदक", fungalDisease: "फफूंद रोग", pestRiskNote: "गर्म और नम परिस्थितियां रोग का जोखिम बढ़ा सकती हैं।", pestRiskTitle: "कीट और रोग जोखिम", pestRiskDescription: "खेत की परिस्थितियों और मौसम पर आधारित जोखिम संकेत।", overallRisk: "कुल जोखिम", riskByThreat: "जोखिम के अनुसार", suggestedPrevention: "सुझावित बचाव",
    prevention1: "उच्च जोखिम वाले क्षेत्रों में पत्तियों की जांच करें।", prevention2: "बिना कारण की पुष्टि किए अनावश्यक छिड़काव न करें।", prevention3: "बारिश के बाद नमी और वर्षा की निगरानी करें।",
    soilTitle: "मिट्टी मॉनिटरिंग", soilDescription: "आपके खेत के लिए मिट्टी और सेंसर संकेत।", soilProfile: "मिट्टी प्रोफाइल", recommendation: "सुझाव", phosphorus: "फॉस्फोरस", organicCarbon: "जैविक कार्बन", texture: "बनावट", soilRecommendation: "वर्तमान सिंचाई बनाए रखें और कटाई के बाद जैविक पदार्थ मिलाएं।",
    analyticsChange: "7 दिन में स्वास्थ्य बदलाव", reportsGenerated: "बनी रिपोर्ट", fieldsMonitored: "निगरानी वाले खेत", recentReports: "हाल की मूल्यांकन रिपोर्ट", generated: "बनी", view: "देखें", downloadPdf: "PDF डाउनलोड करें",
    fieldCreated: "खेत सफलतापूर्वक बन गया। विवरण देखें और निगरानी जारी रखें।", newField: "नया खेत", cropHealthCard: "NDVI, स्वास्थ्य स्कोर और तनाव क्षेत्र।", soilCard: "नमी, pH और पोषक तत्व।", pestCard: "जोखिम संकेत और बचाव के कदम।",
    alertPestText: "नॉर्थ फील्ड में कीट जोखिम बढ़ाने वाली परिस्थितियां दिख रही हैं।", alertWaterText: "दक्षिण-पूर्व क्षेत्र में NDVI और मिट्टी की नमी कम है।", alertRainText: "अगले 48 घंटों में हल्की बारिश की संभावना है।", assistantWelcome: "नमस्ते! मैं FasAI सहायक हूँ। फसल की फोटो अपलोड करें या स्वास्थ्य, मिट्टी, कीट और सिंचाई के बारे में पूछें।", assistantDemo: "डेमो सहायक", assistantDemoResponse: "डेमो जवाब: यहां खेत का स्वास्थ्य, मौसम, मिट्टी और फोटो के संकेतों को मिलाकर सुझाव दिया जाएगा। लाइव सुझाव के लिए इस स्क्रीन को AI API से जोड़ें।", wheat: "गेहूँ", rice: "चावल", maize: "मक्का", cotton: "कपास", vegetables: "सब्ज़ियाँ", loamy: "दोमट", clayLoam: "चिकनी दोमट", sandyLoam: "बलुई दोमट", blackSoil: "काली मिट्टी", alluvial: "जलोढ़ मिट्टी", wind: "हवा", nitrogen: "नाइट्रोजन", potassium: "पोटैशियम", weeklyHealth: "साप्ताहिक स्वास्थ्य", waterStressReport: "पानी की कमी", pestRiskReport: "कीट जोखिम", footerAbout: "हमारे बारे में", footerContact: "संपर्क", footerCopyright: "स्मार्ट फसल जानकारी।"
  },
  mr: {
    home: "मुख्यपृष्ठ", about: "आमच्याबद्दल", howItWorks: "हे कसे कार्य करते", contact: "संपर्क",
    login: "लॉगिन", register: "नोंदणी करा", logout: "लॉगआउट", language: "मराठी",
    getStarted: "सुरुवात करा", learnHow: "हे कसे कार्य करते", watchDemo: "YouTube डेमो पहा", aiMonitoring: "AI आधारित पीक निरीक्षण", slide: "स्लाइड", fieldIntelligence: "FasAI शेत माहिती", liveMonitoring: "लाइव्ह मॉनिटरिंग संकल्पना", seeChanges: "नुकसान होण्याआधी बदल पहा.",
    heroTitle1: "तुमची पिके ठेवा", heroTitle2: "निरोगी आणि सुरक्षित", heroTitle3: "स्मार्ट तंत्रज्ञानाने",
    heroText: "तुमच्या शेतांचे निरीक्षण करा, पिकांचे आरोग्य समजून घ्या आणि AI च्या मदतीने वेळेवर सोपे सल्ले मिळवा.",
    helps: "FasAI तुम्हाला कशी मदत करते",
    uploadPhoto: "पिकाचा फोटो अपलोड करा", uploadText: "पिकाचा स्पष्ट फोटो अपलोड करा आणि FasAI दिसणारी लक्षणे तपासेल.",
    checkHealth: "पिकाचे आरोग्य तपासा", healthText: "सॅटेलाइट, माती, हवामान आणि फोटोमधील संकेत एकत्र करून शेताचे आरोग्य समजून घ्या.",
    recommendations: "सल्ला मिळवा", recText: "सिंचन, पोषण आणि पीक संरक्षणासाठी सोपे आणि उपयुक्त सल्ले मिळवा.",
    monitoring: "आजच तुमच्या पिकांचे निरीक्षण सुरू करा", monitoringText: "तुमची शेते तयार करा, बदल टिपा आणि लहान समस्या मोठ्या नुकसानीत बदलण्याआधी कृती करा.",
    registerNow: "आता नोंदणी करा", secure: "सुरक्षित आणि विश्वासार्ह", farmerFriendly: "शेतकऱ्यांसाठी सोपे", quick: "जलद निकाल", support: "सहाय्य",
    secureText: "तुमचा डेटा सुरक्षित राहतो.", farmerText: "प्रत्येक शेतकऱ्यासाठी सोपी पावले.", quickText: "उपयुक्त माहिती लवकर मिळवा.", supportText: "गरज असेल तेव्हा मदत.",
    dashboard: "डॅशबोर्ड", fields: "शेते", satellite: "सॅटेलाइट मॉनिटर", weather: "हवामान", cropHealth: "पीक आरोग्य",
    alerts: "सूचना", assistant: "AI सहाय्यक", reports: "अहवाल", settings: "सेटिंग्ज", soil: "माती", pestRisk: "कीड जोखीम",
    addField: "नवीन शेत जोडा", search: "शेत शोधा...", fieldDetails: "शेताचा तपशील", healthScore: "आरोग्य गुण",
    healthy: "निरोगी", moderate: "मध्यम", stressed: "ताणलेले", createField: "शेत तयार करा",
    fieldName: "शेताचे नाव", cropType: "पिकाचा प्रकार", area: "क्षेत्रफळ", location: "ठिकाण", soilType: "मातीचा प्रकार",
    sowingDate: "पेरणीची तारीख", harvestingDate: "अपेक्षित कापणी", selectBoundary: "नकाशावर शेताची सीमा निवडा",
    save: "जतन करा", cancel: "रद्द करा", noData: "अजून लाइव्ह डेटा नाही — डेमो डेटा दाखवला जात आहे.",
    overview: "आढावा", recentAlerts: "अलीकडील सूचना", viewAll: "सर्व पहा", temperature: "तापमान",
    humidity: "आर्द्रता", rainfall: "पाऊस", moisture: "मातीतील ओलावा", ndvi: "NDVI",
    healthTrend: "आरोग्य कल", stressZones: "ताण क्षेत्रे", analyze: "शेताचे विश्लेषण करा", back: "मागे",
    send: "पाठवा", askAssistant: "FasAI ला विचारा", uploadImage: "फोटो अपलोड करा", typeMessage: "तुमचा प्रश्न लिहा...",
    reportsDesc: "शेताचे अहवाल, आरोग्य कल आणि डाउनलोड करण्यायोग्य मूल्यांकन सारांश.",
    welcomeDashboard: "पुन्हा स्वागत आहे, शेतकरी 👋", overallCropHealth: "एकूण पीक आरोग्य", totalFields: "एकूण शेते",
    activeAlerts: "सक्रिय सूचना", nextIrrigation: "पुढील सिंचन", requiresAttention: "लक्ष देणे आवश्यक", days: "दिवस",
    northField: "उत्तर शेत", southField: "दक्षिण शेत", eastField: "पूर्व शेत", northWest: "वायव्य", southEast: "आग्नेय", good: "चांगले", activeFields: "सक्रिय शेते", openMap: "सॅटेलाइट मॉनिटर उघडा",
    demoNdvi: "डेमो सॅटेलाइट लेयर • 10 मीटर रिझोल्यूशन लक्ष्य", layerNdvi: "NDVI", layerTrueColor: "खरा रंग", layerMoisture: "ओलावा",
    zoomIn: "झूम इन", zoomOut: "झूम आउट", highPestRisk: "कीडांचा उच्च धोका", waterStress: "पाणी ताण आढळला", rainfallAlert: "पावसाचा इशारा",
    critical: "गंभीर", warning: "इशारा", info: "माहिती", profileRole: "शेतकरी", profileName: "रमेश कुमार",
    menu: "मेन्यू", close: "बंद करा",
    aboutTitle: "शेती माहिती अधिक उपयुक्त बनवणे",
    aboutText: "FasAI शेताचे नकाशे, सॅटेलाइट निरीक्षण, हवामान, माती संकेत आणि AI सहाय्य एका शेतकरी-अनुकूल जागी आणते. उद्देश आहे ताण लवकर ओळखणे, तो कुठे होत आहे हे समजून घेणे आणि पुढील कृती ठरवणे.",
    aboutPoints: [
      ["शेत माहिती", "तुमच्या शेताची सीमा काढा आणि प्रत्येक पीक, क्षेत्रफळ व ठिकाण एका जागी व्यवस्थित ठेवा."],
      ["हवामान-आधारित निर्णय", "तापमान, आर्द्रता, पाऊस आणि मातीतील ओलावा या संकेतांवरून बदलत्या शेत परिस्थिती समजून घ्या."],
      ["पीक आरोग्य निरीक्षण", "NDVI, आरोग्य गुण आणि ताण क्षेत्रे पाहून योग्य ठिकाणी लक्ष केंद्रित करा."],
      ["शेतकरी-प्रथम रचना", "मोठी बटणे, सोपी भाषा आणि मोबाइल-अनुकूल स्क्रीन शेतात वापर सोपा करतात."]
    ],
    aboutClosingTitle: "शेत डेटावरून सोपी पुढची पायरी",
    aboutClosingText: "FasAI वेगवेगळी साधने शोधण्याची गरज कमी करण्यासाठी अनेक संकेत एका जागी आणते. नकाशे, आरोग्य, हवामान, सूचना, अहवाल आणि AI सहाय्य एकत्र जोडलेले राहतात जेणेकरून शेतकरी लवकर निर्णय घेऊ शकेल.",
    howTitle: "FasAI कसे कार्य करते", howText: "FasAI चा प्रवाह सोपा आहे: तुमचे शेत तयार करा, संकेत गोळा करा, पीक-आरोग्य निर्देशांक काढा, ताण ओळखा आणि निकालांना उपयुक्त कृतींमध्ये बदला.",
    howSteps: [
      ["तुमचे शेत तयार करा", "ठिकाण निवडा, पीक आणि माती तपशील भरा, नंतर नकाशावर शेताची सीमा काढा."],
      ["शेत संकेत गोळा करा", "सॅटेलाइट प्रतिमा, हवामान आणि माती निरीक्षण शेत निरीक्षणासाठी माहिती बनतात."],
      ["पीक आरोग्याचे विश्लेषण करा", "FasAI या संकेतांचे आरोग्य गुण, NDVI कल आणि ताण निर्देशकांमध्ये रूपांतर करते."],
      ["लवकर इशारे मिळवा", "सूचना पीक ताण, कीड धोका किंवा असामान्य परिस्थितीसारखे महत्त्वाचे बदल दाखवतात."],
      ["AI सहाय्यकाला विचारा", "पिकाचा फोटो अपलोड करा किंवा प्रश्न विचारा आणि सोपे स्पष्टीकरण व पुढील पावले मिळवा."]
    ],
    contactTitle: "आम्ही मदतीसाठी येथे आहोत", contactText: "उत्पादन प्रश्न, डेमो किंवा तांत्रिक सहाय्यासाठी खालील संपर्क तपशील वापरा.",
    email: "ईमेल", phone: "फोन", location: "ठिकाण", sendMessage: "आम्हाला संदेश पाठवा", name: "नाव", message: "संदेश", sendMessageButton: "संदेश पाठवा",
    emailValue: "support@fasai.example", phoneValue: "+91 00000 00000", locationValue: "भारत • कृषी सहाय्य", contactFaqTitle: "वारंवार विचारले जाणारे प्रश्न",
    contactFaq: [["FasAI मोबाइलवर चालते का?", "होय. इंटरफेस मोबाइल-फर्स्ट आहे जेणेकरून शेतकरी शेतात सहज वापरू शकतील."], ["यात सॅटेलाइट डेटा आहे का?", "डेमो UI Sentinel-2 आधारित निरीक्षणासाठी तयार आहे आणि बॅकएंड डेटा पाइपलाइनशी जोडता येते."], ["मी मराठी वापरू शकतो का?", "होय. वरील भाषा बटणावरून संपूर्ण इंटरफेस बदलता येतो."]],
    otpTitle: "तुमचा मोबाइल नंबर सत्यापित करा", otpText: "आम्ही तुमच्या मोबाइल नंबरवर 6-अंकी OTP पाठवला आहे.", verify: "OTP सत्यापित करा", resend: "OTP पुन्हा पाठवा",
    mobile: "मोबाइल नंबर", fullName: "पूर्ण नाव", enterName: "तुमचे पूर्ण नाव टाका", enterMobile: "तुमचा मोबाइल नंबर टाका",
    continue: "पुढे जा", createAccount: "तुमचे खाते तयार करा", welcomeBack: "पुन्हा स्वागत आहे!",
    loginText: "तुमच्या पिकांचे निरीक्षण सुरू ठेवण्यासाठी लॉगिन करा.", registerText: "FasAI मध्ये सामील व्हा आणि पिकांचे निरीक्षण अधिक स्मार्ट पद्धतीने सुरू करा.",
    invalidOtp: "डेमो OTP 123456 आहे.", demoMode: "डेमो मोड", dashboardDescription: "पीक आरोग्य, शेतातील हालचाल आणि महत्त्वाच्या सूचनांचा सोपा आढावा.",
    satelliteTitle: "सॅटेलाइट मॉनिटरिंग", satelliteDescription: "तुमच्या शेतासाठी डेमो सॅटेलाइट लेयर पहा आणि वनस्पती संकेतांची तुलना करा.",
    satelliteHealthy: "निरोगी वनस्पती संकेत", lowNdviZones: "कमी-NDVI क्षेत्रे", stress: "ताण", healthyLabel: "निरोगी", dataPipeline: "डेटा पाइपलाइन",
    satellitePipelineText: "Sentinel-2 Band 4 + Band 8 → NDVI → field mask → zonal statistics → ML health score.",
    today: "आज", tomorrow: "उद्या", weatherTitle: "हवामान", weatherDescription: "तुमच्या शेताची सद्य स्थिती आणि थोडक्यात अंदाज.", forecast: "5-दिवसांचा अंदाज", rainChance: "पाऊस", demoWeather: "डेमो हवामान डेटा. API की कॉन्फिगर केल्यावर बॅकएंड OpenWeather शी जोडता येईल.",
    alertsDescription: "महत्त्वानुसार शेतातील सूचना आणि सुचवलेल्या पुढील कृती.", markReviewed: "पाहिले म्हणून चिन्हांकित करा", justNow: "आत्ताच", twoHours: "2 तासांपूर्वी", yesterday: "काल",
    cropHealthTitle: "पीक आरोग्य", cropHealthDescription: "आरोग्य गुण, NDVI कल आणि स्थानिक ताण क्षेत्रे.", stressedArea: "ताणलेले क्षेत्र", status: "स्थिती",
    assistantTitle: "AI सहाय्यक", assistantDescription: "पिकाचा फोटो अपलोड करा किंवा तुमच्या शेताबद्दल प्रश्न विचारा.",
    settingsDescription: "भाषा, खाते प्राधान्ये आणि सूचना नियंत्रणे व्यवस्थापित करा.", settingsLanguage: "भाषा", settingsNotifications: "सूचना", enabled: "सुरू",
    fieldsDescription: "तुमची शेते, पिकांचा तपशील आणि सीमा व्यवस्थापित करा.", aphid: "मावा", stemBorer: "खोड किडा", fungalDisease: "बुरशीजन्य रोग", pestRiskNote: "उष्ण आणि दमट परिस्थितीमुळे रोगाचा धोका वाढू शकतो.", pestRiskTitle: "कीड आणि रोग जोखीम", pestRiskDescription: "शेत परिस्थिती आणि हवामानावर आधारित जोखीम निर्देशक.", overallRisk: "एकूण जोखीम", riskByThreat: "धोक्यानुसार जोखीम", suggestedPrevention: "सुचवलेले प्रतिबंध",
    prevention1: "उच्च-जोखीम क्षेत्रातील पानांची तपासणी करा.", prevention2: "कारण निश्चित केल्याशिवाय अनावश्यक फवारणी टाळा.", prevention3: "पावसानंतर आर्द्रता आणि पर्जन्याचे निरीक्षण करा.",
    soilTitle: "माती निरीक्षण", soilDescription: "तुमच्या शेतासाठी माती आणि सेन्सर निर्देशक.", soilProfile: "माती प्रोफाइल", recommendation: "शिफारस", phosphorus: "स्फुरद", organicCarbon: "सेंद्रिय कर्ब", texture: "पोत", soilRecommendation: "सध्याचे सिंचन कायम ठेवा आणि कापणीनंतर सेंद्रिय पदार्थ मिसळा.",
    analyticsChange: "7-दिवसांतील आरोग्य बदल", reportsGenerated: "तयार झालेले अहवाल", fieldsMonitored: "निरीक्षण केलेली शेते", recentReports: "अलीकडील मूल्यांकन अहवाल", generated: "तयार झाले", view: "पहा", downloadPdf: "PDF डाउनलोड करा",
    fieldCreated: "शेत यशस्वीरित्या तयार झाले. तपशील पहा आणि निरीक्षण सुरू ठेवा.", newField: "नवीन शेत", cropHealthCard: "NDVI, आरोग्य गुण आणि ताण क्षेत्रे.", soilCard: "ओलावा, pH आणि पोषकद्रव्ये.", pestCard: "जोखीम निर्देशक आणि प्रतिबंधात्मक कृती.",
    alertPestText: "उत्तर शेतात कीड धोका वाढवणाऱ्या परिस्थिती दिसत आहेत.", alertWaterText: "आग्नेय क्षेत्रात NDVI आणि मातीतील ओलावा कमी आहे.", alertRainText: "पुढील 48 तासांत हलक्या पावसाची शक्यता आहे.", assistantWelcome: "नमस्कार! मी FasAI सहाय्यक आहे. पिकाचा फोटो अपलोड करा किंवा आरोग्य, माती, कीड आणि सिंचनाबद्दल विचारा.", assistantDemo: "डेमो सहाय्यक", assistantDemoResponse: "डेमो उत्तर: येथे शेताचे आरोग्य, हवामान, माती आणि फोटो संकेत एकत्र करून सल्ला दिला जाईल. लाइव्ह सल्ल्यासाठी ही स्क्रीन AI API शी जोडा.", wheat: "गहू", rice: "भात", maize: "मका", cotton: "कापूस", vegetables: "भाज्या", loamy: "पोयट्याची माती", clayLoam: "चिकण-पोयट्याची माती", sandyLoam: "वाळू-पोयट्याची माती", blackSoil: "काळी माती", alluvial: "गाळाची माती", wind: "वारा", nitrogen: "नत्र", potassium: "पालाश", weeklyHealth: "साप्ताहिक आरोग्य", waterStressReport: "पाणी ताण", pestRiskReport: "कीड जोखीम", footerAbout: "आमच्याबद्दल", footerContact: "संपर्क", footerCopyright: "स्मार्ट पीक माहिती."
  }
};
